{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-key",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.25.0.jar",
          "url": "adventure-key-4.25.0.jar",
          "size": 11368,
          "sha512": "5e6a2c8b4f85229eb9f8cc6236986e6976597932723fbaab196f1a0e394b38d3923266031d34f2dda6324176f4b37758c3f7d23cadba03f28606f03cc225e6fb",
          "sha256": "cec8f0abf642df0e627bf5a9fff6f17cbb620ea6fe05f2162b96cad1564d8857",
          "sha1": "eadeff9eeaa46f76de3f31fdff1d8e952273cf04",
          "md5": "34aec174134a718817e3aa641a835664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.25.0.jar",
          "url": "adventure-key-4.25.0.jar",
          "size": 11368,
          "sha512": "5e6a2c8b4f85229eb9f8cc6236986e6976597932723fbaab196f1a0e394b38d3923266031d34f2dda6324176f4b37758c3f7d23cadba03f28606f03cc225e6fb",
          "sha256": "cec8f0abf642df0e627bf5a9fff6f17cbb620ea6fe05f2162b96cad1564d8857",
          "sha1": "eadeff9eeaa46f76de3f31fdff1d8e952273cf04",
          "md5": "34aec174134a718817e3aa641a835664"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-key-4.25.0-javadoc.jar",
          "url": "adventure-key-4.25.0-javadoc.jar",
          "size": 105662,
          "sha512": "e1ebfd76f3c8504939f71a0474d6bb4ac2908bc02c6e1fa7d002ab992ce86f0d6b4e9ec82b3a90b9e2be41bba555e9ee347532f2c4bd679919627fc851369be6",
          "sha256": "cea7b69bc1f4e885aef99b939982a7713b5b8a3d2cf35bce58060e48cb0db472",
          "sha1": "84174668db8a62517ccfe10b4dd5aae72dae39e3",
          "md5": "261ea1f4caa39bbfe2988b954f856b76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-key-4.25.0-sources.jar",
          "url": "adventure-key-4.25.0-sources.jar",
          "size": 13405,
          "sha512": "6ab2c94f6f3cc45eeb181634b186630b9e4967dc21b6bf637401c5e7aa118cb6f3ad524915002d876b5105f337811dfdc355422d5f00759e694a8e9002de8901",
          "sha256": "133cc1f89181ac4618219e985c8a12ca9db3164b9942cdd68b10917c21334c2b",
          "sha1": "754f157c636fd0eb9733553912a8bf97d6437f0b",
          "md5": "308ea94db11fd0c8de8d542226e6a020"
        }
      ]
    }
  ]
}
