{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mojang",
    "module": "datafixerupper",
    "version": "8.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "datafixerupper-8.0.16.jar",
          "url": "datafixerupper-8.0.16.jar",
          "size": 724313,
          "sha512": "e48c978fe722cf1e0c7d604dda90f85211bc0cff262f300f33bf0293a50da7c67fa0daafe2b511189f41578893c58f187912437b058787e685bec6b09af0711a",
          "sha256": "ffc138bc2596c291781b0d5e211ccac51f0f2345f27fc2742f335cedf7e2870d",
          "sha1": "67d4de6d7f95d89bcf5862995fb854ebaec02a34",
          "md5": "d932ac637b6d83e6c45a8f269fe81e3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.1.2-jre"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.12"
          }
        }
      ],
      "files": [
        {
          "name": "datafixerupper-8.0.16.jar",
          "url": "datafixerupper-8.0.16.jar",
          "size": 724313,
          "sha512": "e48c978fe722cf1e0c7d604dda90f85211bc0cff262f300f33bf0293a50da7c67fa0daafe2b511189f41578893c58f187912437b058787e685bec6b09af0711a",
          "sha256": "ffc138bc2596c291781b0d5e211ccac51f0f2345f27fc2742f335cedf7e2870d",
          "sha1": "67d4de6d7f95d89bcf5862995fb854ebaec02a34",
          "md5": "d932ac637b6d83e6c45a8f269fe81e3b"
        }
      ]
    }
  ]
}
