{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "AutoRenamingTool",
    "version": "2.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "cli-utils",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "AutoRenamingTool-2.0.5.jar",
          "url": "AutoRenamingTool-2.0.5.jar",
          "size": 103697,
          "sha512": "18c32d60ce4cb727ac0e95a09abde0e00603630b92953e79a4c3c268a273dcb88e3d619a066de29906612415828fb86eb34693173c1a6358f484c8d459792f6e",
          "sha256": "352c926b98d716cecf016cd39ee97490b75a095bff8a9513f7b3fd8b1fff62c7",
          "sha1": "11a274db4f67c372da7c9ec722173d6da3088dd9",
          "md5": "29a6c454eb4018eafa9cd1107772c675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "6.0-alpha-3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.5"
          }
        },
        {
          "group": "net.neoforged.javadoctor",
          "module": "gson-io",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "net.neoforged",
          "module": "srgutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.neoforged.installertools",
          "module": "cli-utils",
          "version": {
            "requires": "2.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "AutoRenamingTool-2.0.5.jar",
          "url": "AutoRenamingTool-2.0.5.jar",
          "size": 103697,
          "sha512": "18c32d60ce4cb727ac0e95a09abde0e00603630b92953e79a4c3c268a273dcb88e3d619a066de29906612415828fb86eb34693173c1a6358f484c8d459792f6e",
          "sha256": "352c926b98d716cecf016cd39ee97490b75a095bff8a9513f7b3fd8b1fff62c7",
          "sha1": "11a274db4f67c372da7c9ec722173d6da3088dd9",
          "md5": "29a6c454eb4018eafa9cd1107772c675"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AutoRenamingTool-2.0.5-all.jar",
          "url": "AutoRenamingTool-2.0.5-all.jar",
          "size": 747289,
          "sha512": "c65028785007c12ba74876aafd9f235495848004ee2f7c7c8a0ef5348c268d4d594e63c4f42a2f29c3ecf39bc2789b6a3f78eda1000e91f272c7182863d4f597",
          "sha256": "f9df307e2b276188b6ff5bf3385849ab0a6b1a032eb6af0301b8b50b1a6cc73e",
          "sha1": "a36b8df52b712c44f083ba046114d2546dbcada0",
          "md5": "8e7afd2b55baeef7097d8808caa26ebb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AutoRenamingTool-2.0.5-sources.jar",
          "url": "AutoRenamingTool-2.0.5-sources.jar",
          "size": 43599,
          "sha512": "7e74e1bc4e072d0a77debd9ad757558478310060580b65462fb8db64520882b2e054dec0131f4ef978e467cac027f3de2fcc46fa0f80a22d91bbb14c68a5d436",
          "sha256": "af2601e87ae4c457b9881767b512b3595afaa889223befd23175a77aec7f599a",
          "sha1": "3227c76ce69607ef74a447d47edeade0944ef720",
          "md5": "be02bee3026f4acd6322de0a3b0b5096"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AutoRenamingTool-2.0.5-javadoc.jar",
          "url": "AutoRenamingTool-2.0.5-javadoc.jar",
          "size": 136862,
          "sha512": "e94df634c1a9beb9efc42d6826bdac2912099d1e0f0849c16d0425588263ab7952a0a345fa9911e4dfb0744cec12643e991a05302d83974ee9c5ab5ed5852c46",
          "sha256": "6f82e5eef3d2c0a6a89e3dea1e8cafa631b88001af37df29cde4b58dae079f1a",
          "sha1": "c14680215c1d1f8dfa36c50f66a03ac9acc45156",
          "md5": "59bfaaa11d1d6ba72de1267ad769651f"
        }
      ]
    }
  ]
}
