{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-annotations",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.18.1.jar",
          "url": "jackson-annotations-2.18.1.jar",
          "size": 78488,
          "sha512": "490bde45ecdda09d5c48ba1f5df5042ceab254d8d7e44052820850f7488ecbfcb27f3d5211173bb762b9b8b9f6471076137cc150ee2e772caaddf78ec07200f",
          "sha256": "b7f9df5dac9a85f47fdb2769455ee8ba9cf2fe9b7c4cf636e0aec83479d7882f",
          "sha1": "8f9aa97e7fb44d4bea829061625472b0f6199923",
          "md5": "e6e6d0e87b374c710d29188c9c0c512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-annotations-2.18.1.jar",
          "url": "jackson-annotations-2.18.1.jar",
          "size": 78488,
          "sha512": "490bde45ecdda09d5c48ba1f5df5042ceab254d8d7e44052820850f7488ecbfcb27f3d5211173bb762b9b8b9f6471076137cc150ee2e772caaddf78ec07200f",
          "sha256": "b7f9df5dac9a85f47fdb2769455ee8ba9cf2fe9b7c4cf636e0aec83479d7882f",
          "sha1": "8f9aa97e7fb44d4bea829061625472b0f6199923",
          "md5": "e6e6d0e87b374c710d29188c9c0c512"
        }
      ]
    }
  ]
}
