{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-core",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.18.1.jar",
          "url": "jackson-core-2.18.1.jar",
          "size": 597814,
          "sha512": "134e1ff9d955c2784280236c2fcb584d744fdca8c83ccb93af55d1295a6482698b53367779b20df3adf12e1c792b084312b9c0139e9a0d92c5512239a0872966",
          "sha256": "ebe19596ad19f7a0514c8bb8f7b0acf85239a4eff5ae03229e9760d268d29c22",
          "sha1": "9e2284c539e2dedd2aa1487c781e20a0f575d695",
          "md5": "74983885c7bd1f9aaa3935115fd1dd3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-2.18.1.jar",
          "url": "jackson-core-2.18.1.jar",
          "size": 597814,
          "sha512": "134e1ff9d955c2784280236c2fcb584d744fdca8c83ccb93af55d1295a6482698b53367779b20df3adf12e1c792b084312b9c0139e9a0d92c5512239a0872966",
          "sha256": "ebe19596ad19f7a0514c8bb8f7b0acf85239a4eff5ae03229e9760d268d29c22",
          "sha1": "9e2284c539e2dedd2aa1487c781e20a0f575d695",
          "md5": "74983885c7bd1f9aaa3935115fd1dd3f"
        }
      ]
    }
  ]
}
