{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "examination-string",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "examination-string-1.3.0.jar",
          "url": "examination-string-1.3.0.jar",
          "size": 13135,
          "sha512": "22624cb3c9f0555d968534611a492d1e06dc028ace9f7ce3550e52400b57ba779a5b2e1da3e2af5f2cb83b7f197796344652c76f74ddb0b8f126748530bfadea",
          "sha256": "7d01fc25a4bb3af0e1662685455f4541fbf4626216ea5846e455c1491e156b8c",
          "sha1": "6f34afef5c54ccce4996bc321abf77518b55b4bd",
          "md5": "9e4752ea3f53ae45e736c9d8f016f23d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "examination-string-1.3.0.jar",
          "url": "examination-string-1.3.0.jar",
          "size": 13135,
          "sha512": "22624cb3c9f0555d968534611a492d1e06dc028ace9f7ce3550e52400b57ba779a5b2e1da3e2af5f2cb83b7f197796344652c76f74ddb0b8f126748530bfadea",
          "sha256": "7d01fc25a4bb3af0e1662685455f4541fbf4626216ea5846e455c1491e156b8c",
          "sha1": "6f34afef5c54ccce4996bc321abf77518b55b4bd",
          "md5": "9e4752ea3f53ae45e736c9d8f016f23d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "examination-string-1.3.0-javadoc.jar",
          "url": "examination-string-1.3.0-javadoc.jar",
          "size": 403835,
          "sha512": "67efe0a500c53692b1b7febdf5811b8faf293449e977b4a341623fe59867ebf675059757b23528c6d0f59faa6d3772064eedd73f4f8ff33802aa670d688b344d",
          "sha256": "04dde8a99cf0e1d4078253b8e3f99ceab2a20ae83793ed24b066c47927dabddb",
          "sha1": "ceacfca8382471b74d41b3a44d64cc2e1b3fbed4",
          "md5": "410f55c484e4c5c080adfb8509304630"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "examination-string-1.3.0-sources.jar",
          "url": "examination-string-1.3.0-sources.jar",
          "size": 8462,
          "sha512": "717e1aff6cc4388a1b546d7f051546985ddb36529ed43fed7f6f5a4806f704f4590eeeb0ac13f50307ff930208688f14985a3043f98213a8dd3e2661463a4df1",
          "sha256": "ec922af37b1d4538de715697a938a6c74bda9482adaea2e6ba09e70a500b4d03",
          "sha1": "d06d07677cf2022bdf38136ba550aea9852cc1bd",
          "md5": "eccc1713411a97952f471cf06c646943"
        }
      ]
    }
  ]
}
