{
  "formatVersion": "1.1",
  "component": {
    "group": "io.papermc.jst",
    "module": "jst-cli-bundle",
    "version": "1.0.68+paper.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jst-cli-bundle-1.0.68+paper.2-SNAPSHOT.jar",
          "url": "jst-cli-bundle-1.0.68+paper.2-SNAPSHOT.jar",
          "size": 34815419,
          "sha512": "27268b60826bfcf03b207f3738a4a459acdd65c768f2ff12ce098535849cbd6802d99949cebab0402fb7d71a223abbf0494131ef9fe729348caf8c26faf57ef0",
          "sha256": "e32080ed478348d3cc24438e6a850da43d2bfd0185792489cd3ffa8d692547bf",
          "sha1": "ffe05b42557f872c6c0560794bcc4423e0722239",
          "md5": "281e158b06322533d2602464478c2ba4"
        }
      ]
    }
  ]
}
