{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.datatype",
    "module": "jackson-datatype-jsr310",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.18.1.jar",
          "url": "jackson-datatype-jsr310-2.18.1.jar",
          "size": 131058,
          "sha512": "b385664a77e31ca83d2cc2895e35fbff34c5d00bd7a96bbd4909da6f537f2e97d5c22efe52a186d29c3dae44be32f5043238b663b68d4b11265b7e42e58881d6",
          "sha256": "5fc66c0ed3ab1fe5f95dfeadffe127412b4b6661a9fd87be732d05b782a809f4",
          "sha1": "64d488c200a9cfac2d230713c6b82753004c6a6d",
          "md5": "5e378c5ce81b679ff3aa0bc96e3196d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-datatype-jsr310-2.18.1.jar",
          "url": "jackson-datatype-jsr310-2.18.1.jar",
          "size": 131058,
          "sha512": "b385664a77e31ca83d2cc2895e35fbff34c5d00bd7a96bbd4909da6f537f2e97d5c22efe52a186d29c3dae44be32f5043238b663b68d4b11265b7e42e58881d6",
          "sha256": "5fc66c0ed3ab1fe5f95dfeadffe127412b4b6661a9fd87be732d05b782a809f4",
          "sha1": "64d488c200a9cfac2d230713c6b82753004c6a6d",
          "md5": "5e378c5ce81b679ff3aa0bc96e3196d9"
        }
      ]
    }
  ]
}
