{
  "formatVersion": "1.1",
  "component": {
    "group": "net.kyori",
    "module": "adventure-api",
    "version": "4.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.25.0.jar",
          "url": "adventure-api-4.25.0.jar",
          "size": 453704,
          "sha512": "808426d8409c8e5f69695e208d07cb7214adb5cb3e2e41d2f19485ed5f3d2d4825076a97edcb0834fbad15ad3825b8f1fc3499d51e414f44ff5ed51f3a0ce4a8",
          "sha256": "8e281bf1357ff91af9783a6c24276b483d8154a7b3cab5b04e909e6bf5e72c9d",
          "sha1": "6bd10494eeb2f8eadce7226db4445e8728985cbb",
          "md5": "f7cfc9db3159df1f9b37eed8a15f69a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.25.0.jar",
          "url": "adventure-api-4.25.0.jar",
          "size": 453704,
          "sha512": "808426d8409c8e5f69695e208d07cb7214adb5cb3e2e41d2f19485ed5f3d2d4825076a97edcb0834fbad15ad3825b8f1fc3499d51e414f44ff5ed51f3a0ce4a8",
          "sha256": "8e281bf1357ff91af9783a6c24276b483d8154a7b3cab5b04e909e6bf5e72c9d",
          "sha1": "6bd10494eeb2f8eadce7226db4445e8728985cbb",
          "md5": "f7cfc9db3159df1f9b37eed8a15f69a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.25.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-key",
          "version": {
            "requires": "4.25.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-api",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "examination-string",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "26.0.2-1"
          }
        }
      ],
      "files": [
        {
          "name": "adventure-api-4.25.0-javadoc.jar",
          "url": "adventure-api-4.25.0-javadoc.jar",
          "size": 898036,
          "sha512": "5305a8f0dc49e2ad293fdf2927ec3fa87e8f87442d96ce40172d1611a49481806d1d747eac33631ccf5d7966434fb2d60b913631293be181dd2d13a7e51d56ce",
          "sha256": "b39026735085067cd50cb7351ea9c2572fc5cc3000d875da59f8dc83f849f6d5",
          "sha1": "e6e399e8799e7932d90efd98fbf53177ac650596",
          "md5": "d2ede1d0375c3e46a84b6987ce982c49"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "adventure-api-4.25.0-sources.jar",
          "url": "adventure-api-4.25.0-sources.jar",
          "size": 356179,
          "sha512": "aa6b5744bd3f9e866cb7967a2eeb682ee4e8a97347c36d315c1752c11d1f94d5db2700c8adc60b605a371329ab57c94bc90507196c47fb86003cb07e6db20a22",
          "sha256": "310078e822435ca7a03c8882755a6d85dead67800bf9b31b157ca4a0ba20b0a9",
          "sha1": "72c11a7b5a20485304c336e1df1780862c080fa9",
          "md5": "707a2ca82eb18dead66cccfa73ad18ba"
        }
      ]
    }
  ]
}
