{
  "formatVersion": "1.1",
  "component": {
    "group": "org.spongepowered",
    "module": "configurate-core",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.16"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.36.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0.jar",
          "url": "configurate-core-4.2.0.jar",
          "size": 364528,
          "sha512": "cd73ef2d7c15bf17abc3960ed119ae449e59467412d67ed87b529cf655a2a2404089bee4c33d48a0a55b409538f0c7c47c4630828a01fb7a0efe96ff72dbbacb",
          "sha256": "06c1e9f7789a189af0c0156ebe9f469da7cc674233f43e8133c83131edd9f7e0",
          "sha1": "7b322107fae38a6b8d30690b6b512696c49d9d66",
          "md5": "66d61a57ea0a7017071df0fbe0fd3e65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.16"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0.jar",
          "url": "configurate-core-4.2.0.jar",
          "size": 364528,
          "sha512": "cd73ef2d7c15bf17abc3960ed119ae449e59467412d67ed87b529cf655a2a2404089bee4c33d48a0a55b409538f0c7c47c4630828a01fb7a0efe96ff72dbbacb",
          "sha256": "06c1e9f7789a189af0c0156ebe9f469da7cc674233f43e8133c83131edd9f7e0",
          "sha1": "7b322107fae38a6b8d30690b6b512696c49d9d66",
          "md5": "66d61a57ea0a7017071df0fbe0fd3e65"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.leangen.geantyref",
          "module": "geantyref",
          "version": {
            "requires": "1.3.16"
          }
        },
        {
          "group": "net.kyori",
          "module": "option",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.36.0"
          }
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.0"
          }
        }
      ],
      "files": [
        {
          "name": "configurate-core-4.2.0-javadoc.jar",
          "url": "configurate-core-4.2.0-javadoc.jar",
          "size": 859134,
          "sha512": "e1cb17bc85579aa18efc6dc8d6abbc31ee5a6d7c617202b9135cd6d0722c205a1dc9e597d01bbc129ccc780be40ee8bf23d7021eddb54a3eb234e32e29464f06",
          "sha256": "3d3d63eabba8905f3af40143f9cddcf3afbd5159fe152e39eb4e11a74b2696ed",
          "sha1": "390ac1f7521ba131593b4e7700cd7888529919bb",
          "md5": "d0d50bbdfa1e5453fcf27918c282d039"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configurate-core-4.2.0-sources.jar",
          "url": "configurate-core-4.2.0-sources.jar",
          "size": 221851,
          "sha512": "fef76307b76a052e0b7b61d72808e880ecd34030ed5e8a598a12b8ecdbb2dcc8d490d635b3170dfb7375dbbf03e41437014d7c0a688e41d9ab73eed19c40b684",
          "sha256": "a68070bc275f219980f633ba446521d2a7af5385bcb8bbf7eea4922af6611de0",
          "sha1": "c1e1d6aa464c88d5641941d29c766b03cd819daa",
          "md5": "4f3be419ca6d43334c2c174473a89995"
        }
      ]
    }
  ]
}
