{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.18.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.18.1.jar",
          "url": "jackson-databind-2.18.1.jar",
          "size": 1657971,
          "sha512": "e72dd9d5d2418bbbdebccd1eae97becf9462b8c861e697a0dad733bc6c11ffe2f5e2281a757a3cbfaee6891a0a95ec87dde1ee601a445ba0f3ad64687140f3b3",
          "sha256": "711bc3bf86d31d02968b9279efb07a6ad60adfc0baa0e9fe66d71a0ac2556234",
          "sha1": "66547d0c6c2f9e022019499308f09bebbf30ab2e",
          "md5": "4d5e91d0c1171c388cb87ee034e08c1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.18.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.18.1.jar",
          "url": "jackson-databind-2.18.1.jar",
          "size": 1657971,
          "sha512": "e72dd9d5d2418bbbdebccd1eae97becf9462b8c861e697a0dad733bc6c11ffe2f5e2281a757a3cbfaee6891a0a95ec87dde1ee601a445ba0f3ad64687140f3b3",
          "sha256": "711bc3bf86d31d02968b9279efb07a6ad60adfc0baa0e9fe66d71a0ac2556234",
          "sha1": "66547d0c6c2f9e022019499308f09bebbf30ab2e",
          "md5": "4d5e91d0c1171c388cb87ee034e08c1c"
        }
      ]
    }
  ]
}
